# Generated by Django 4.2.23 on 2025-07-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название процедуры')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('Employees', models.ManyToManyField(to='employees.employeemodel')),
            ],
        ),
    ]
