# Generated by Django 4.2.23 on 2025-07-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemodel',
            old_name='Employees',
            new_name='employees',
        ),
    ]
