# Generated by Django 4.2.23 on 2025-07-31 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('services', '0002_rename_employees_servicemodel_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeemodel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicemodel')),
            ],
        ),
    ]
