# Generated by Django 4.2.23 on 2025-07-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='phone',
        ),
    ]
