# Generated by Django 4.2.23 on 2025-07-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_clientmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
